### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by frozenpandaman** [irrwahn/svg2ass#2]
FYI, anyone building on Mac should change the Makefile line `STRIP = strip -s` to `STRIP = strip -S` before running `make install` or `make release`.

You can then use it by running `./svg2ass < yourfile.svg`.

**Comment by irrwahn** [comment]
Thank you very much for the hint!  I placed a note to this effect in `README.md`, as I did not want to clutter the Makefile with OS detection code.

**Comment by frozenpandaman** [comment]
Thanks so much! (Without this change I was running into an error, and found the solution in some other repo that involved makefiles.)

And thanks for the extremely useful tool too! :)
